### ISSUE TITLE
http://ldsguitarhymns.com is down

### ISSUE THREAD

**Issue by trevordmiller** [dlbunker/ldsguitarhymns#1]
Hey @dlbunker, I recently purchased both volumes of your LDS Guitar Hymns book through Amazon. They are fantastic, thank you! The books mentions a few resources at http://ldsguitarhymns.com and it looks like this is the repo for it. I'm not sure if you know already, but the app is currently down - Heroku is throwing a `Failed to load resource: the server responded with a status of 503 (Service Unavailable)` error:

![fullsizeoutput_54f](https://user-images.githubusercontent.com/5497885/40579056-ec5309ee-60dc-11e8-9d88-898c9c4d825f.jpeg)

**Comment by dlbunker** [comment]
Hey,
Thanks for letting me know. I'm currently running the site on Heroku's free
dynos and I think it has run out of uptime for the month but will reset
next month. As far as any of the additional resources you might be
interested in, just let me know and I can send them to you directly.

Dan

On Sat, May 26, 2018 at 12:05 PM, Trevor D. Miller <notifications@github.com

**Comment by trevordmiller** [comment]
@dlbunker Sounds good, I'll check it out next month. I personally really like [Zeit Now for hosting](https://zeit.co/now) - for static sites they have infinite scaling and hosting for free.
